config/routes.rb
Matsoz::Application.routes.draw do



  resources :entries
  resources :stats
  resources :exports





  root :to => 'entries#index'


end

app/models/entry.rb
# encoding: utf-8

class String
  def to_downcase_english
    self.downcase.gsub('ç', 'c').gsub('ğ', 'g').gsub('ı', 'i').gsub('ö', 'o').gsub('ş', 's').gsub('ü', 'u')
                 .gsub('Ç', 'c').gsub('Ğ', 'g').gsub('İ', 'i').gsub('Ö', 'o').gsub('Ş', 's').gsub('Ü', 'u')    
  end
  
  def to_downcase_turkish
     self.downcase.gsub('Ç', 'ç').gsub('Ğ', 'ğ').gsub('İ', 'i').gsub('I', 'ı').gsub('Ö', 'ö').gsub('Ş', 'ş').gsub('Ü', 'ü')
  end
  
  def to_upcase_turkish
    self.upcase.gsub('ç', 'Ç').gsub('ğ', 'Ğ').gsub('i', 'İ').gsub('ı', 'I').gsub('ö', 'Ö').gsub('ş', 'Ş').gsub('ü', 'Ü')
  end
  
  def self.compare_turkish_letters(letter1, letter2)
    alphabet = " 0123456789_abcçdefgğhıijklmnoöpqrsştuüvwxyz"
    
    letter1 = letter1.to_downcase_turkish
    letter2 = letter2.to_downcase_turkish
    
    index1 = alphabet.index(letter1);
    index2 = alphabet.index(letter2);
    
    if index1
      if index2
        if index1 > index2
          return 1
        elsif index1 < index2
          return -1
        else
          return 0
        end
      else
        return -1
      end
    elsif index2
      return 1
    else
      return letter1 <=> letter2
    end
  end
  
  def compare_turkish (other)
    if self == ""
      if other == ""
        return 0
      else
        return -1
      end
    elsif other == ""
      return 1
    else
      comparison = String.compare_turkish_letters(self[0], other[0])
      if comparison == 0
        return self[1..-1].compare_turkish(other[1..-1])
      else
        return comparison
      end
    end
  end
end

class Entry < ActiveRecord::Base
  has_attached_file :thumbnail,
                    :storage => :s3,
                    :bucket => ENV['S3_BUCKET_NAME'],
                    :s3_credentials => {
                      :access_key_id => ENV['S3_KEY'],
                      :secret_access_key => ENV['S3_SECRET']
                    }
  
  attr_accessible :word, :meaning, :thumbnail, :additionalInfo

  validates :word, :presence => true
  
  def javascript_file
    return 'animations/' + self.word.to_downcase_english.gsub(/\s+/, '_') + '.js'
  end
end

app/controllers/entries_controller.rb
# encoding: utf-8

class EntriesController < ApplicationController  
  before_filter :set_all_entries, :create_word_list
  
  def set_all_entries
    puts params[:word_list]
    if params[:word_list]
      words = params[:word_list].split(',')
    end
    
    if !words
      @all_entries = Entry.order(:word).all
    else
      @all_entries = []
      words.each do |word|
        entry = Entry.where(:word => word).first
        if (entry)
          @all_entries << entry
        end
      end
    end
  end
  
  def create_word_list
    
    if params[:word_list]
      words = params[:word_list].split(',')
    end
    
    @word_list = {}
    letters = ['a', 'b', 'c', 'ç', 'd', 'e', 'f', 'g', 'h', 'ı', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'ö', 'p', 'r', 's', 'ş', 't', 'u', 'ü', 'v', 'y', 'z'];
    letters.each do |letter|
      @word_list[letter] = []
    end
    
    
    if (!words)
      letters = ['a', 'b', 'c', 'ç', 'd', 'e', 'f', 'g', 'h', 'ı', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'ö', 'p', 'r', 's', 'ş', 't', 'u', 'ü', 'v', 'y', 'z'];
      letters.each do |letter|
        entries = Entry.find(:all, :conditions => ['word LIKE ? OR word LIKE ?', "#{letter}%", "#{letter.to_upcase_turkish}%"], :order => 'word ASC')
      
        puts entries
      
        entries = entries.sort do |entry1, entry2|
          entry1.word.compare_turkish(entry2.word)
        end
      
        entries.each do |entry|
        
          selected = false
          if entry.id.to_s == params[:id].to_s
            @current_letter = letter
            selected = true
          end

          if @exporting
            if @index_page
              link = "entries/" + entry.id.to_s + ".html"
            else
              link = entry.id.to_s + ".html"
            end


            @word_list[letter] << {
              :word => entry.word,
              :selected => selected,
              :link => link
            }
          else
            @word_list[letter] << {
              :word => entry.word,
              :selected => selected,
              :link => entry_path(entry)
            }
           end
        end
      end
    else
      # words = ['açınım', 'boyut', 'doğal sayılarla çarpma işlemi', 'eş küpler', 'kesirleri sıralama', 'paralelkenar']
      words.each do |word|
        entry = Entry.where(:word => word).first
        
        if (entry)
          letter = word.chars.first
      
          selected = false
          if entry.id.to_s == params[:id].to_s
            @current_letter = letter
            selected = true
          end

          if @exporting
            if @index_page
              link = "entries/" + entry.id.to_s + ".html"
            else
              link = entry.id.to_s + ".html"
            end

            @word_list[letter] << {
              :word => entry.word,
              :selected => selected,
              :link => link
            }
          else
            @word_list[letter] << {
              :word => entry.word,
              :selected => selected,
              :link => entry_path(entry)
            }
          end      
        end
      end
    end
  end
  
  def index
    
  end
  
  def show

    @entry = Entry.find(params[:id])

    chunks = @entry.meaning.split(/=>|\*\*/)
    delimiters = @entry.meaning.scan(/=>|\*\*/)
    
    @chunks = []

    errorFound = false
    
    @chunks.push({chunks.shift => nil})
    
    while !(delimiters.empty?)
      delimiter = delimiters.shift
  
      if delimiter == "**"
        chunk = chunks.shift
        delimiter = delimiters.shift
        
        if delimiter == "**"
          @chunks.push({chunk => Entry.find_by_word(chunk.to_downcase_turkish)})
          @chunks.push({chunks.shift => nil})
        elsif delimiter == "=>"
          destination = chunks.shift
          @chunks.push({chunk => Entry.find_by_word(destination.to_downcase_turkish)})
          
          delimiter = delimiters.shift
          if delimiter == "**"
            @chunks.push({chunks.shift => nil})
          else
            errorFound = true
          end
        else
          errorFound = true
        end
      else
        errorFound = true
      end
    end
  end
  
  def new

  end
  
  def create
    entry = Entry.create(params[:entry])
    if entry
      flash[:notice] = 'Entry created successfully'
      redirect_to entry_path(entry)
    end
  end
  
  def edit
    @entry = Entry.find(params[:id])
  end
  
  def update
    @entry = Entry.find params[:id]
    @entry.update_attributes!(params[:entry])
    flash[:notice] = "#{@entry.word} was successfully updated."
    redirect_to entry_path(@entry)
  end
  
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    flash[:notice] = "#{@entry.word} was deleted successfully."
    redirect_to entries_path
  end
end

app/views/entries/edit.html.haml
%h1= "Update #{@entry.word}"

= form_for @entry do |form|
  = label :entry, :word, 'Word'
  %br
  
  = text_field :entry, 'word'
  %br
  = label :entry, :meaning, 'Meaning'
  %br
  = text_area :entry, 'meaning'
  %br
  = label :entry, :additionalInfo, 'Additional Info'
  %br
  = text_area :entry, 'additionalInfo'
  %br
  
  Thumbnail:
  = form.file_field :thumbnail
  %br
  
  = submit_tag 'Update Entry'

= button_to "Delete #{@entry.word}", entry_path(@entry), :method => :delete, :confirm => 'Are you sure?'
= link_to "Back to #{@entry.word}", entry_path(@entry)

app/views/entries/index.html.haml

- content_for(:head) do
  %meta{'http-equiv'=>'Content-Type', 'content' => 'text/html; charset=UTF-8'}
  = javascript_include_tag 'main.js'
  - if @ipad
    = javascript_include_tag 'splash_ipad.js'
    = stylesheet_link_tag 'theme/blue/matsoz_blue_ipad.css'
    = stylesheet_link_tag 'theme/blue/matsoz_splash_ipad.css'
  - else
    
    = javascript_include_tag 'splash.js'
    = stylesheet_link_tag 'theme/blue/matsoz_blue.css'
    = stylesheet_link_tag 'theme/blue/matsoz_splash.css'
  = stylesheet_link_tag 'theme/bes/matsoz_bes.css'
  = stylesheet_link_tag 'theme/blue/matsoz_dialog.css'
  :javascript
    var wordList = #{@word_list.to_json};
    var currentLetter = 'a';
  - if @exporting
    :javascript
      var exportedPage = true;
  - else
    :javascript
      var exportedPage = false;
  :javascript
    var indexPage = true;
#container
  - if !@ipad
    -##words_list
    -#  - @all_entries.each do |entry|
    -#    %p= link_to entry.word, entry_path(entry)
    .navlinktasiyici
      - letters = []
      - @word_list.keys.each do |key|
        - if @word_list[key].length != 0
          - letters << key

      - index = 0
      - letters.each do |letter|
        - if index == 0
          - piece = 'harf_sol_1'
        - elsif index == 1
          - piece = 'harf_sag_1'
        - elsif index == letters.length - 1
          - if index % 2 == 0
            - piece = 'harf_sol_4'
          - else
            - piece = 'harf_sag_4'
        - elsif index == letters.length - 2
          - if index % 2 == 0
            - piece = 'harf_sol_4'
          - else
            - piece = 'harf_sag_2'
        - elsif index % 4 == 2
          - piece = 'harf_sol_2'
        - elsif index % 4 == 3
          - piece = 'harf_sag_2'
        - elsif index % 4 == 0
          - piece = 'harf_sol_2'
        - elsif index % 4 == 1
          - piece = 'harf_sag_2'

        = link_to letter.to_upcase_turkish + letter, '#', {:class => 'navlink navposition ' + piece, :data=>{:letter => letter}, :onclick=>'return false'}
        - index = index + 1

  %div.btn_home
    %img{:src=>'/assets/theme/blue/ui_img/btn_home.png', :width=>'40', :height=>'36', :alt=>'Ana Sayfa'}
  %div.btn_info
    %img{:src=>'/assets/theme/blue/ui_img/btn_info.png', :width=>'40', :height=>'36', :alt=>'Bilgi'}
  %div.btn_print
    %img{:src=>'/assets/theme/blue/ui_img/btn_print.png', :width=>'40', :height=>'36', :alt=>'Etkileşimi Yazdır'}

  %div.sozcuktasiyici
    - @all_entries.each do |entry|
      - if @exporting
        - if entry == @entry
          %a{:href => entry.id.to_s + ".html", :class => 'sozcuklink sozcukselected'} #{entry.word}
        - else
          %a{:href => entry.id.to_s + ".html", :class => 'sozcuklink'} #{entry.word}
      - else
        - if entry == @entry
          = link_to entry.word, entry_path(entry), {:class => 'sozcuklink sozcukselected'}
        - else
          = link_to entry.word, entry_path(entry), {:class => 'sozcuklink'}
  .matsoz_logo
    =image_tag("theme/blue/ui_img/matsoz5_logo.png")

-#= link_to 'Create new entry',  new_entry_path

app/views/entries/new.html.haml
%h1 Create New Entry

= form_tag entries_path do
  = label :entry, :word, 'Word'
  %br
  = text_field :entry, 'word'
  %br
  = label :entry, :meaning, 'Meaning'
  %br
  = text_area :entry, 'meaning'
  %br
  = label :entry, :additionalInfo, 'Additional Info'
  %br
  = text_area :entry, 'additionalInfo'
  %br
  
  
  = submit_tag 'Create Entry'

app/views/entries/show.html.haml

- content_for(:head) do
  %meta{'http-equiv'=>'Content-Type', 'content' => 'text/html; charset=UTF-8'}
  = javascript_include_tag 'main.js'
  - if @ipad
    = stylesheet_link_tag 'theme/blue/matsoz_blue_ipad.css'
    = stylesheet_link_tag 'theme/blue/matsoz_dialog.css'
    = stylesheet_link_tag 'theme/bes/matsoz_bes.css'
  - else

    = stylesheet_link_tag 'theme/blue/matsoz_blue.css'
    = stylesheet_link_tag 'theme/blue/matsoz_dialog.css'
    = stylesheet_link_tag 'theme/bes/matsoz_bes.css'
  = stylesheet_link_tag 'print.css', :media => 'print'
  - begin
    = javascript_include_tag @entry.javascript_file
  - rescue

  - if Rails.env.development?
    = javascript_include_tag 'development.js'

  - if @ipad
    :javascript
      var forIpad = true;
  - else
    :javascript
      var forIpad = false;

  - if @exporting
    :javascript
      var exportedPage = true;
  - else
    :javascript
      var exportedPage = false;

  :javascript
    var wordList = #{@word_list.to_json};
    var currentLetter = '#{@current_letter}';

#container
  - if !@ipad
    %div.matsoz_logo
      %img{:src=>'/assets/theme/bes/logo_bes.png'}
    .navlinktasiyici
      - letters = []
      - @word_list.keys.each do |key|
        - if @word_list[key].length != 0
          - letters << key

      - index = 0
      - letters.each do |letter|
        - if index == 0
          - piece = 'harf_sol_1'
        - elsif index == 1
          - piece = 'harf_sag_1'
        - elsif index == letters.length - 1
          - if index % 2 == 0
            - piece = 'harf_sol_4'
          - else
            - piece = 'harf_sag_4'
        - elsif index == letters.length - 2
          - if index % 2 == 0
            - piece = 'harf_sol_4'
          - else
            - piece = 'harf_sag_2'
        - elsif index % 4 == 2
          - piece = 'harf_sol_2'
        - elsif index % 4 == 3
          - piece = 'harf_sag_2'
        - elsif index % 4 == 0
          - piece = 'harf_sol_2'
        - elsif index % 4 == 1
          - piece = 'harf_sag_2'

        = link_to letter.to_upcase_turkish + letter, '#', {:class => 'navlink navposition ' + piece, :data=>{:letter => letter}, :onclick=>'return false'}
        - index = index + 1


    -#%div.btn_prev
    -#  %img{:src=>'/assets/theme/blue/ui_img/btn_prev.png', :width=>'60', :height=>'46', :alt=>'Önceki'}
    -#%div.btn_next
    -#  %img{:src=>'/assets/theme/blue/ui_img/btn_next.png', :width=>'60', :height=>'46', :alt=>'Sonraki'}
    %div.btn_home
      %img{:src=>'/assets/theme/blue/ui_img/btn_home.png', :width=>'40', :height=>'36', :alt=>'Ana Sayfa'}
    %div.btn_info
      %img{:src=>'/assets/theme/blue/ui_img/btn_info.png', :width=>'40', :height=>'36', :alt=>'Bilgi'}
    %div.btn_print
      %img{:src=>'/assets/theme/blue/ui_img/btn_print.png', :width=>'40', :height=>'36', :alt=>'Etkileşimi Yazdır'}

    %div.sozcuktasiyici
      - @all_entries.each do |entry|
        - if @exporting
          - if entry == @entry
            %a{:href => entry.id.to_s + ".html", :class => 'sozcuklink sozcukselected'} #{entry.word}
          - else
            %a{:href => entry.id.to_s + ".html", :class => 'sozcuklink'} #{entry.word}
        - else
          - if entry == @entry
            = link_to entry.word, entry_path(entry), {:class => 'sozcuklink sozcukselected'}
          - else
            = link_to entry.word, entry_path(entry), {:class => 'sozcuklink'}

  %div.tanim
    - if @entry.thumbnail?
      %div.simgebg
        = image_tag('theme/blue/ui_img/simge_bg.png', {:width => 139, :height => 143, :style => "position:absolute; top: 0px; left: 0px;"})
        %div.simge
          - if @exporting
            = image_tag('/assets/symbols/' + @entry.id.to_s + '.png', {:style => "position:absolute; top: 0px; left: 0px;"})
          - else
            = image_tag(@entry.thumbnail.url, {:style => "position:absolute; top: 0px; left: 0px;"})
    %strong.name
      = @entry.word + ": "
    - @chunks.each do |chunk|
      - chunk.each do |key, value|
        - if value == nil
          - if key != nil
            =key.gsub(' ', "\n")
        - else
          - if @exporting
            %a{:href => value.id.to_s + ".html"} #{key}
          - else
            = link_to key, entry_path(value)
    %div.additional_info
      - if @entry.additionalInfo
        %em
          = @entry.additionalInfo

  %div{:class=>'ornek ornek_border sablon'}
    %div{:class =>'ornekbaslik ornekbaslik_bg'}
  - if @ipad
    #container2
      %div{:class => 'mavikontrol sablon'}
      %div{:class => 'etkilesimalan sablon'}
  - else
    %div{:class => 'mavikontrol sablon'}
    %div{:class => 'etkilesimalan sablon'}